[package]
name = "burn-contracts"
version = "0.1.0"
keywords = ["burn", "tensor", "contracts", "testing"]
categories = ["development-tools::testing"]
edition = "2021"
repository = "https://github.com/crutcher/burn-contracts"
license = "MIT"

[dependencies]
burn = { version = "~0.16.0", features = [] }

[dev-dependencies]
burn = { version = "~0.16.0", features = ["ndarray"] }

[features]
testing = []
